import type { NextPage } from "next";
import Link from "next/link";
import Image from "next/image";
import styles from "./Home.module.scss";

import Layout from "../components/Layout/Layout";
import Seo from "../components/Seo/Seo";
import ButtonPrimary from "../components/ButtonPrimary/ButtonPrimary";
import ButtonSecondary from "../components/ButtonSecondary/ButtonSecondary";
import FeatureCard from "../components/FeatureCard/FeatureCard";
import Headline from "../components/Headline/Headline";
import Newsletter from "../components/Newsletter/Newsletter";

const Home: NextPage = () => {
  const meta = [
    { name: "description", content: "Generated by create next app" },
  ];

  const feautres = [
    {
      image: {
        urlImage: "/icon.svg",
        alt: "Icon,",
      },
      title: "Instant Features",
      text: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat.",
    },
    {
      image: {
        urlImage: "/icon.svg",
        alt: "Icon,",
      },
      title: "Instant Features",
      text: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat.",
    },
    {
      image: {
        urlImage: "/icon.svg",
        alt: "Icon,",
      },
      title: "Instant Features",
      text: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat.",
    },
  ];

  return (
    <Layout isMenu={true} isFooter={true}>
      <Seo title="Landing Template" meta={meta} />
      <section className={styles.headline}>
        <h1>Landing template for startups</h1>
        <p>
          Our landing page template works on all devices, so you only have to
          set it up once, and get beautiful results forever.
        </p>
        <div className={styles.buttons}>
          <ButtonPrimary href="/" text="Start free trial" />
          <ButtonSecondary href="/" text="Learn more" />
        </div>
      </section>
      <section className={styles.video}>
        <Link href="/">
          <a className={styles.play}></a>
        </Link>
      </section>
      <Headline
        title="Build up the whole picture"
        text="Excepteur sint occaecat cupidatat non proident, sunt in culpa qui
          officia deserunt mollit anim id est laborum — semper quis lectus nulla
          at volutpat diam ut venenatis."
      />
      <section className={styles.icons}>
        {feautres &&
          feautres.map((feature, index) => (
            <FeatureCard
              key={index}
              image={{
                urlImage: feature.image.urlImage,
                alt: feature.image.alt,
              }}
              title={feature.title}
              text={feature.text}
            />
          ))}
      </section>
      <section className={styles.solutions}>
        <div className={styles.tag}>
          <span>Reach goals that matter</span>
        </div>
        <Headline
          title="One product, unlimited solutions"
          text="Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia 
          deserunt mollit laborum — semper quis lectus nulla."
        />
        <div className={styles.details}>
          <div>
            <h2>More speed. Less spend</h2>
            <h3>Keep projects on schedule</h3>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
            <ul>
              <li>Duis aute irure dolor in reprehenderit</li>
              <li>Excepteur sint occaecat</li>
              <li>Amet consectetur adipiscing elit</li>
            </ul>
          </div>
          <div>
            <Image
              src="/Illustration.jpg"
              alt="Illuatration"
              width={540}
              height={405}
            />
          </div>
        </div>
      </section>
      <Newsletter />
    </Layout>
  );
};

export default Home;
