import { NextPage } from "next/types";
import Link from "next/link";
import { Formik, Form, Field } from "formik";

import styles from "./Signin.module.scss";
import stylesForm from "../styles/form.module.scss";

import Layout from "../components/Layout/Layout";
import Seo from "../components/Seo/Seo";
import ButtonGoogleAuthentication from "../components/ButtonGoogleAuthentication/ButtonGoogleAuthentication";
import Title from "../components/Title/Title";

const Signin: NextPage = () => {
  const meta = [
    { name: "description", content: "Generated by create next app" },
  ];

  return (
    <Layout isMenu={false} isFooter={false}>
      <Seo title="Sign in" meta={meta} />
      <div className={styles.content}>
        <Title text="Welcome. We exist to make entrepreneurism easier." />
        <ButtonGoogleAuthentication />
        <Formik
          initialValues={{
            fullName: "",
            password: "",
          }}
          onSubmit={(values) => {
            console.log(values);
          }}
        >
          <Form className={stylesForm.form}>
            <label htmlFor="fullName">
              Full Name <span>*</span>
            </label>
            <Field
              name="fullName"
              type="text"
              placeholder="First and last name"
            />
            <label htmlFor="password">
              Password <span>*</span>
            </label>
            <Field name="password" type="password" placeholder="Password" />
            <button type="submit">Sign in</button>
            <p className={stylesForm.signin}>
              Don’t you have an account?{" "}
              <Link href="/signup">
                <a>Sign up</a>
              </Link>
            </p>
          </Form>
        </Formik>
      </div>
    </Layout>
  );
};

export default Signin;
