import { NextPage } from "next";
import Link from "next/link";
import { Formik, Form, Field } from "formik";

import styles from "./Signup.module.scss";
import stylesForm from "../styles/form.module.scss";

import Layout from "../components/Layout/Layout";
import Seo from "../components/Seo/Seo";
import ButtonGoogleAuthentication from "../components/ButtonGoogleAuthentication/ButtonGoogleAuthentication";
import Title from "../components/Title/Title";

const Signup: NextPage = () => {
  const meta = [
    { name: "description", content: "Generated by create next app" },
  ];
  return (
    <Layout isMenu={false} isFooter={false}>
      <Seo title="Sign up" meta={meta} />
      <Title text="Welcome. We exist to make entrepreneurism easier." />
      <div className={styles.content}>
        <ButtonGoogleAuthentication />
        <Formik
          initialValues={{
            fullName: "",
            company: "",
            email: "",
            password: "",
          }}
          onSubmit={(values) => {
            console.log(values);
          }}
        >
          <Form className={stylesForm.form}>
            <label htmlFor="fullName">
              Full Name <span>*</span>
            </label>
            <Field
              name="fullName"
              type="text"
              placeholder="First and last name"
            />
            <label htmlFor="company">
              Company Name <span>*</span>
            </label>
            <Field
              name="company"
              type="text"
              placeholder="Your company or app name"
            />
            <label htmlFor="email">
              Work Email <span>*</span>
            </label>
            <Field
              name="email"
              type="email"
              placeholder="you@yourcompany.com"
            />
            <label htmlFor="password">
              Password <span>*</span>
            </label>
            <Field name="password" type="password" placeholder="Password" />
            <p>
              I agree to be contacted by Open PRO about this offer as per the
              Open PRO{" "}
              <Link href="/">
                <a>Privacy Policy</a>
              </Link>
              .
            </p>
            <button type="submit">Sign up</button>
            <p className={stylesForm.signin}>
              Already using Open PRO?{" "}
              <Link href="/signin">
                <a>Sign in</a>
              </Link>
            </p>
          </Form>
        </Formik>
      </div>
    </Layout>
  );
};

export default Signup;
